# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-16 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninja_app', '0004_auto_20190915_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='Some notes'),
        ),
    ]
