# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-16 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninja_app', '0005_author_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='books',
            new_name='books_id',
        ),
    ]
