# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-16 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninja_app', '0006_auto_20190915_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='books_id',
        ),
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='dojo_ninja_app.Book'),
        ),
    ]
