# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-25 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='password',
            field=models.CharField(default='password', max_length=20),
            preserve_default=False,
        ),
    ]
