# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-25 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_restaurant_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.FloatField(default=0),
        ),
    ]
