# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-25 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190925_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='updated_at',
        ),
    ]
