# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-25 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_restaurant_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
