# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-20 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_author_book_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.CharField(default=2, max_length=45),
            preserve_default=False,
        ),
    ]
